ssllib.c

Without this commit I am getting error when compiling on freebsd:
"ssllib.c:82:42: error: use of undeclared identifier 'PTHREAD_MUTEX_INITIALIZER'"

Added missing include of config.h

---

ssl4pl.c

LibreSSL does not have key_arg and key_arg_length members
in SSL_SESSION struct because it obsoleted SSLv2.
Check if the feature macro is set and do not use those
members if it is. In that case do not use FUNCTOR_session_key1
at all.

Check for OPENSSL_NO_SSL2

---

https.pl

This example will be quite often used to provide HTTPS servers.

remove unnecessary single quotes

---

ssl.doc
ssl.pl
ssl4pl.c
ssllib.c
ssllib.h

This is the reason for #21 : `host/1` and `port/1` were not specified (because they were not documented).

DOC: SSL: document port/1 and host/1 options for ssl_context/3

---

http_ssl_plugin.pl

Passing the option is backwards compatible (no error). However, it is
unnecessary since the connection is now established differently.

CLEANUP: No longer use obsolete port/1 option in HTTP SSL plugin.

---

ssl.doc
ssl.pl
ssl4pl.c
ssllib.c
ssllib.h

This is a **callback**-based implementation of SNI.
Conceptually, I like the callback approach a lot. Users who care about performance can precreate the required contexts.

Server Name Indication (SNI) for the SSL server

---

ssl.pl
ssl4pl.c
ssllib.c
ssllib.h

Please consider merging this change, which is only incompatible with the immediately preceding development release (7.3.30). Very likely, the HTTP Unix daemon is the only current user of this option (pull request forthcoming).
Generalizing this option as per this pull request is important to accommodate different current and future authentication methods, and also aligns the option format with that of `certificate/1`.
In addition, handling PEM-encoded keys simplifies the code.

MODIFIED: ssl_context/3: key/1 argument is now the PEM-encoded key (string or atom)

---

ssl.pl
ssl4pl.c
ssllib.c
ssllib.h

This is work in progress on a port of `library(ssl)` to the OpenSSL **1.1.0** API.
Since the OpenSSL API is complex enough as is, I am dropping backwards compatibility with prior versions.
I will extend this branch with any progress I make on the port, using additional commits.
I am marking commits with **TODO** where I temporarily comment out code instead of porting it. 
Currently, it compiles, but yields:
<pre>
$ swipl -g server server.pl
<b>Cannot read back application data</b>
</pre>
At this point, I'm also considering dropping OpenSSL, and switching to a different TLS&nbsp;library altogether. It may be easier to use a different library than to keep up with&nbsp;this.

Port to OpenSSL 1.1.0

---

ssllib.c

This is necessary due to a change in behaviour of OpenSSL 1.1.0c: When
encountering EOF, SSL_read() now returns -1 instead of 0 (as it did
previously).
Note that this behaviour may change again in future versions, since it
is currently subject to debate:
https://github.com/openssl/openssl/issues/1903
However, 1.1.0c is already published and must be accommodated, and
further, this change will remain valid even if the return value of
SSL_read() changes again, since we now explicitly check for EOF.
Test case:
?- http_open('https://www.metalevel.at', In, []),
copy_stream_data(In, current_output).
Without this commit, we get with OpenSSL 1.1.0c:
ERROR: copy_stream_data/2: I/O error in read on stream (0x2718700) (Success)

PORT: Handle EOF portably, making copy_stream_data/2 etc. work in OpenSSL 1.1.0c

---

client.pl
server.pl

This makes the examples work also if only a subset of packages is installed.

FIXED: Load library(socket) in client and server examples.

---

client.pl
server.pl
ssl.pl
ssl4pl.c
ssllib.c
ssllib.h

close_notify when closing the connection.
In addition, enabling this option raises an exception when EOF is
encountered without either side having initiated a TLS shutdown. This
mitigates truncation attacks, in which an adversary may cut the
connection or inject TCP FIN packets to simulate EOF.
This attack only applies to protocols that are *not* self-terminating
and is therefore extremely rare in practice (well-designed protocols
are self-terminating). However, the client/server examples are of this
type, and therefore this option is now enabled in the examples.

ADDED: New option close_notify(+Boolean), making the server send

---

ssl.pl
ssllib.c

Earlier OpenSSL versions do not set a curve by default. We use
prime256v1 in such cases, as before, but no longer override the new
library defaults with this curve.
This commit makes stronger curves automatically available when using
newer OpenSSL versions, unless users have explicitly asked for a
specific curve. A major attraction of OpenSSL 1.1.0 is X25519, which
is the new default curve in that version for ECDH.
To disable ECDH entirely, use the cipher_list/1 option (also as before).
In the future, ecdh_curve/1 will be superseded by a new option that
binds SSL_CTX_set1_groups. However, this currently affects both ECDH
and ECDSA, and we will adopt the eventual solution of OpenSSL.
See https://github.com/openssl/openssl/issues/2033 for more information.

ENHANCED: Use OpenSSL default curves (ecdh_curve/1) in OpenSSL >= 1.1.0.

---

Makefile.in
configure.in
crypto.pl
crypto4pl.c
ssl.doc
ssl.pl
ssl4pl.c
ssllib.c
ssllib.h
test_ssl.pl

This is my suggestion, as discussed in #76.
It passes all tests with OpenSSL 1.1.0 as well as earlier versions.
Please review and merge if applicable. It will be a pleasure for me to add more bindings to `library(crypto)` in the future.

ADDED: library(crypto)

---

Makefile.in
crypto4pl.c
cryptolib.c
cryptolib.h
ssllib.c
ssllib.h

This allows you to use the cryptographic predicates without loading
the full SSL library.

ENHANCED: Completely disentangle library(crypto) from libssl.so

---

crypto4pl.c
cryptolib.c
cryptolib.h
ssl4pl.c
ssllib.c
ssllib.h

In older OpenSSL versions, this is necessary to make `library(crypto)` thread-safe.

ENHANCED: Share thread safety code in cryptolib.c

---

http_ssl_plugin.pl
ssl.doc
ssl.pl
ssl4pl.c
test_ssl.pl

These hooks let us:
- *exchange* the certificate of a running&nbsp;server
- launch servers with *multiple* certificates
- specify *default* certificates.
Due to their [**logical purity**](https://www.metalevel.at/prolog/purity), all of this is completely *thread-safe*!
To the best of my knowledge, none of the more widely used HTTPS servers lets you do&nbsp;this. In fact, not even OpenSSL&nbsp;itself lets you exchange the certificate of a context in a thread-safe&nbsp;way.
These features are also available when using the HTTP Unix&nbsp;daemon.
Enjoy!

New hooks: https:ssl_server_create_hook/2 and https:ssl_server_open_client_hook/2

---

ssl.pl
ssl4pl.c

This makes it possible to later override a hook that is created for
example by the HTTP Unix daemon when the context is created.
This predicate lets you enjoy the convenience of the HTTP Unix daemon
together with the flexibility of custom code, among other benefits.
Note again how [**logical purity**](https://www.metalevel.at/prolog/purity) makes this predicate thread safe. This
is especially interesting in this case because not even OpenSSL itself
is thread safe for such use cases!

ADDED: ssl_set_sni_hook/3, allowing to set the SNI callback of a context

---

ssl.pl
ssl4pl.c

Thus, all properties of the original context are now correctly retained when
using the new predicates ssl_set_sni_hook/3 and ssl_add_certificate_key/4.

ENHANCED: Transfer certificate revocation list when copying a context.

---

ssl.pl
ssl4pl.c

The first two commits are almost self-explanatory.
The third commit removes an option that is almost completely useless, has for years been documented as obsolete, and can cause confusion with a different, much more important&nbsp;option.
Please see the commit messages for more details.

Memory correction and cleanup

---

crypto.pl
crypto4pl.c
ssl.pl
ssl4pl.c

The new predicates `crypto_term_hash/3`, `crypto_file_hash/3` etc. finally make the digest&nbsp;algorithms that are currently available in library(md5) and library(sha) available under a unified interface, by providing bindings to OpenSSL functionality.
Further OpenSSL digest algorithms can be made available easily with this interface.
Please review especially the Prolog **interface** predicates provided by this patch.
I think this interface is simpler than that of `library(sha)`, for example<sup>1</sup>.
These interface predicates subsume existing libraries that ship with SWI and make it easy to provide new digest algorithms in the future. For example, one of the first new additions will be the `BLAKE` hashing algorithms that are available since OpenSSL&nbsp;1.1.0c. I will include them …

ADDED: library(crypto): New interface predicates for computing hashes

---

crypto.pl

Note that libcrypto.so is loaded also if only library(ssl) is used!
Therefore, if you are writing a web application with HTTPS or even
only access a single HTTPS URL, using library(crypto) does not load
any additional resources, in contrast to using the other hash libraries.

DOC: Explain the relation of library(crypto) to other hash libraries.

---

configure.in
crypto.pl
crypto4pl.c

These algorithms are available when using OpenSSL 1.1.0 or greater.
Any digest algorithms that OpenSSL implements in future versions can
be made available easily through the interface of library(crypto).

ADDED: library(crypto): BLAKE digest algorithms, blake2s256 and blake2b512

---

Makefile.in
crypto.doc
crypto.pl
cryptolib.md
test_ssl.pl
xmldsig.pl
xmlenc.pl

This pull request makes the library ready for the stable release:
- 4 mostly superfluous and unused predicates have been removed to simplify the interface and make it more uniform. Use an empty option list instead.
- The new and **bidirectional** predicate `hex_bytes/2` is now available.
- The documentation is now more structured and self-contained, using **Markdown**.
Please review (especially the `mkdir -p summaries.d` that now appears in `Makefile.in` to generate the directory that `libtotex` expects), merge if applicable, and happy 7.4!

Finalization for 7.4

---

configure.in
crypto.pl
crypto4pl.c
cryptolib.c
cryptolib.md
ssl4pl.c

A **hash-based message authentication code** (HMAC) can be used to
simultaneously verify the integrity *and* authenticity of data.
The new `hmac(+Key)` option is now available for *all* hash predicates
of `library(crypto)`, enabling HMAC computation with a given key.
This option is a significant generalization of `hmac_sha/4` from
`library(sha)`: Starting with OpenSSL 1.1.0, hash-based MACs are now
available for *all* provided digest algorithms with `library(crypto)`.
`library(xmldsig)` is a use case that needs this functionality.

ADDED: hmac/1 option for all hash predicates of library(crypto).

---

ssl.doc
ssl.pl
ssl4pl.c

`ssl_set_options/3` is an important building block for tweaking existing contexts in hooks.
**Note that the existing context is necessary because it may contain certificates and keys that are no longer readable at the time the hook is invoked!**
This new feature finally lets us get rid of `ssl_set_sni_hook/3`, which is currently only necessary in extremely obscure setups and only complicates the SSL&nbsp;interface. The second commit does&nbsp;this.
Please see the respective commit messages for a more detailed description.
Related discussion:
https://github.com/SWI-Prolog/plweb/issues/23
Note that not *all* parameters can currently be tweaked after creation of the context. Notably, it is currently not documented what OpenSSL does if existing certificates are replaced. Related issue: …

ADDED: New predicate ssl_set_options/3 for tweaking SSL contexts

---

crypto.pl
crypto4pl.c
cryptolib.md

The new predicates crypto_password_hash/[2,3] implement PBKDF2-SHA512
and will also implement additional algorithms in the future.
For security reasons, it is highly recommended that you use
crypto_password_hash/2 instead of crypt/2. This lets you store the
hashes of user passwords in a reasonably secure way.

ADDED: library(crypto): Password-based key derivation.

---

configure.in
crypto.pl
crypto4pl.c
cryptolib.md

The new predicate crypto_data_hkdf/4 lets you concentrate possibly
dispersed entropy of existing data and then expand it to the desired
length.  This allows you to derive keys and initialization vectors for
cryptographic routines, notably the symmetric encryption predicates.

ADDED: library(crypto): HMAC-based key derivation function (HKDF).

---

crypto.pl
crypto4pl.c
cryptolib.md

Previously, sha1 was the default. I expect zero impact from this
change, because every programmer who uses these predicates *must*
think about the actual hash algorithm that ought to be used on signing
or verification. It has for several years been known that SHA1 cannot
be considered secure, and in fact even a concrete collision was
recently found. Thus, any existing application must have been migrated
to a different algorithm due to security considerations, making the
old default inapplicable. Also the internal uses of these predicates
all specify the actual algorithm as an option to these predicates, and
hence no further changes were needed anywhere within SWI-Prolog due to
this modification.
The primary purpose of this change is to signal that security is being
taken seriously here, …

MODIFIED: rsa_sign/4 and rsa_verify/4 now use sha256 by default.

---

crypto.pl
crypto4pl.c

There are different types of "contexts" in OpenSSL. We need to
distinguish hash contexts from cipher contexts in preparation of
incremental encryption, which will become available in SWI 7.8.
The public library(crypto) API is not affected by this change.
There are 3 predicates for incremental hashing:
crypto_context_new/2
crypto_data_context/3
crypto_context_hash/2
There may be slightly better names, and I will reconsider the API of
library(crypto) once incremental encryption is also available.  It
should be rather easy to smoothly transition the hash API because
these predicates are rarely used. crypto_file_hash/3 is more important
for hashes of large files, and that name is perfectly OK.

CLEANUP: "context" --> "hash_context" in internal definitions.

---

ssl.pl
ssl4pl.c

TLS 1.3 is available with OpenSSL 1.1.1 or later.

ADDED: Configuration support for TLS 1.3 in min/max_protocol_version.

---

http_ssl_plugin.pl

This ensures that HTTP timeouts are properly propagated.
Example:
:- use_module(library(http/thread_httpd)).
:- use_module(library(http/http_dispatch)).
:- use_module(library(http/http_unix_daemon)).
:- http_handler(/, handle_request, []).
handle_request(_Request) :-
format("Content-type: text/plain~n~n"),
format("Hello!").
http:ssl_server_open_client_hook(_SSL0, SSL, _Options) :-
ssl_context(server, SSL,
[certificate_file('etc/server/server-cert.pem'),
key_file('etc/server/server-key.pem'),
password(apenoot1)]).
Put this code in http_server.pl and launch the server with:
$ p=etc/server; swipl https_server.pl --https \
--interactive --port=4090  --timeout=0.1
Then connect with:
$ openssl s_client -connect localhost:4090
It should terminate almost instantly.

ENHANCED: Always set close_parent(true) in HTTP server hooks.

---

CMakeLists.txt

As discussed in SWI-Prolog/swipl-devel#358.
CMAKE "re-roots" the paths to find programs during crosscompilation, this prevents that behaviour so that we can use the `openssl` binary on the host.

FIX: don't use crosscompiling paths to find openssl

---

cryptolib.c

LibreSSL has got EVP_MD_CTX_(free|new) but not OPENSSL_zalloc, the
compiler complains about the last being defined but never used.
As OPENSSL_zalloc is only used in the EVP_MD_CTX_new, it is only
defined iff the EVP_MD_CTX_(new|free) pair is defined.

fixes warning about OPENSSL_zalloc defined but never used

---

cryptolib.c

Looks like I was not testing on OpenSSL 1.1.1 before.

Fix reuse of run-once in OpenSSL1.1.1+

---

saml.pl
xmldsig.pl

There was a bit of betroth here - this PR fixes SAML and XMLdsig code to use the new certificate API, and fixes a bug where we assumed the canonicalization method would be the default

Saml fixes

---

CMakeLists.txt

The little program is meant to produce a warning if the first argument of X509_get0_signature(&psig, &palg, data) is not declared const. It's compiled with -Werror. On my Windows, a warning interferes this test, namely, that data is uninitialized.

Avoid warning on uninitialized variable

---

crypto4pl.c
cryptolib.c
ssl4pl.c

LibreSSL 3.5.0.
Most structs that were previously defined in the following headers
are now opaque as they are in OpenSSL 1.1:
bio.h, bn.h, comp.h, dh.h, dsa.h, evp.h, hmac.h, ocsp.h, rsa.h,
x509.h, x509v3.h, x509_vfy.h

PORT: Fix building with modern LibreSSL versions
